# Generated by Django 6.0.2 on 2026-03-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('electronics', 'Elektronika'), ('fashion', 'Moda'), ('collectibles', 'Kolekcionarstvo'), ('books', 'Knjige'), ('other', 'Ostalo')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
    ]
