# Generated by Django 6.0.2 on 2026-03-03 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_auction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_price',
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
