# Generated by Django 6.0.2 on 2026-03-03 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='starting_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
