# Generated by Django 6.0.2 on 2026-03-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
