# Generated by Django 6.0.3 on 2026-03-03 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
